### PR TITLE
Support Custom Template Generator

### PR DESCRIPTION
**Pull request by dustindclark**
- Support Custom Template Generators (in both dynamic and generated templates)
- Ignore embedded many to many relationships in scaffolded forms (database structure doesn’t support this)
- Upgrade GORM dependency
- Set Grails version to 2.5.0
- Ignore IntelliJ files

### CODE REVIEW

**Comment by dustindclark** [comment]
@lhotari / @graemerocher , can you guys take a look at this when you get a chance?  There is no way (currently) to override the default template generator that is used in the generate-views scripts, and this pull request adds this capability.  If you have feedback/concerns, please let me know.  Thanks.

**Comment by jeffbrown** [comment]
Is there a reason that you are referring to `Holders.config.` instead of `application.config` in the `doWithSpring` block?

**Comment by jeffbrown** [comment]
See https://github.com/dustindclark/grails-scaffolding/commit/07514cefe43389bd3234efb7d7707cfc655594fc#diff-5a334a6064e30fa9b5d33961abe109ceR70.

**Comment by jeffbrown** [comment]
`Holders` is also referenced at https://github.com/dustindclark/grails-scaffolding/commit/07514cefe43389bd3234efb7d7707cfc655594fc#diff-480319a4fefa232453de414092bde3a3R80.

**Comment by jeffbrown** [comment]
There may be several unrelated changes in the PR.  Is the template generator change dependent on any of these or are these addressing separate concerns?:

https://github.com/grails-plugins/grails-scaffolding/pull/25/files#diff-065ee6c616db877d7e0b2ed0bd457d81L1
https://github.com/grails-plugins/grails-scaffolding/pull/25/files#diff-d9ffa53bd42b8af025cf46822ea3f22aR15
https://github.com/grails-plugins/grails-scaffolding/pull/25/files#diff-e5355e9634e3902ac701e47f7b2d1e70R22

**Comment by jeffbrown** [comment]
https://github.com/grails-plugins/grails-scaffolding/commit/749b227a89de0b6c6fc87f0f422734c14ab376fa

**Comment by dustindclark** [comment]
@jeffbrown , thanks for merging.  To answer your questions:

* No, support for a custom template generator is not dependent on the other changes.  Only the _GrailsGenerate.groovy and doWithSpring changes are required to support a custom generator.  The other changes are related to better support for embedded domain classes.  I intend to contribute further enhancements, but I have to recreate them on my own time (off the clock).
* No particular reason for using Holders instead of application.confg in doWithSpring.  In _GrailsGenerate, we're running in the context of a script...so (I think) Holders is the only option.

**Comment by jeffbrown** [comment]
>  In _GrailsGenerate, we're running in the context of a script...so (I think) Holders is the only option.

I don't think that is correct.  I think you should be able to do something like `includeTargets << grailsScript("_GrailsInit")` at the top of the script and then just refer to `config` instead of using `Holders`.

**Comment by dustindclark** [comment]
I will give that a shot.  Thanks.

Dustin

Sent from my iPhone

On Apr 15, 2015, at 6:15 PM, Jeff Scott Brown <notifications@github.com>
wrote:

In _GrailsGenerate, we're running in the context of a script...so (I think)
Holders is the only option.

I don't think that is correct. I think you should be able to do something
like includeTargets << grailsScript("_GrailsInit") at the top of the script
and then just refer to config instead of using Holders.

—
Reply to this email directly or view it on GitHub
<https://github.com/grails-plugins/grails-scaffolding/pull/25#issuecomment-93594720>
.

**Pull request closed without merging**
